### ISSUE TITLE
Support vektra/mockery

### ISSUE THREAD

**Issue by ccoVeille** [bhundven/golang-pre-commit#24]
Please see discussion here

- https://github.com/vektra/mockery/issues/791

You can take a look at the PR I made and you could reuse

- https://github.com/vektra/mockery/pull/795

Please also find the explanations why I closed my PR in mockery repository

- https://github.com/vektra/mockery/issues/791#issuecomment-2645818897

**Comment by bhundven** [comment]
I'm just curious how this would be used.
I wasn't familiary with mockery, so I had to read into that one a bit.
It seems to me that this would be used in a pre-commit like this (`.pre-commit-config.yaml`):
```yaml
repos:
  - repo: https://github.com/bhundven/golang-pre-commit
    rev: v1
    hooks:
      - id: go-build
      - id: go-mockery
      - id: go-unit-tests
```
right? Or mockery runs the tests?

**Comment by ccoVeille** [comment]
Mockery is about generating code that can be used in tests.

It generates it from code my looking at interfaces. It's a kind of `go:generate`

Mocks can be used in tests of the package itself, but also by code using the Go module as library in external code.

For this reason, it's important to update code from source.

The best example I'm able to think about is to consider an interface had two methods

```go
type Whatever interface {
	Foo() string
	Bar() string
}
```

So the code and mocks supported Foo() and Bar()

Now the maintainer removes Bar() from the interface, if mockery is not called, the Mock will still have Bar()

Tests will pass for people using mocked Bar in their tests, but Bar was removed, so their code will be broken without them to know.

TL; DR; Using it as a pre-commit hook is important because it will make sure to update the mocks before committing

Mockery doesn't launch test, it generates code that can be used by the tests

There is no dependency between running test, using go build and launching mockery

The user defining the pre-commit hooks in their .pre-commit-config.yaml will be the one who knows what they need to launch and in what order

**Comment by bhundven** [comment]
Gotcha. I'll get something for you to review tomorrow.

**Comment by ccoVeille** [comment]
Please also consider including the people who were looking for this feature. I mentioned them in this message

- https://github.com/vektra/mockery/pull/795#issuecomment-2645820276

**Comment by bhundven** [comment]
Test adding mockery:
```yaml
repos:
  - repo: https://github.com/bhundven/golang-pre-commit
    rev: feat/mockery
    hooks:
      - id: generate-mockery
```
Let me know.
